In [265]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [266]:
df=pd.read_csv("car_purchasing.csv", encoding="latin1")

In [267]:
df

,customer name,customer e-mail,country,gender,age,annual Salary,credit card debt,net worth,car purchase amount
0,Martina Avila,cubilia.Curae.Phasellus@quisaccumsanconvallis.edu,Bulgaria,0,41.851720,62812.09301,11609.380910,238961.2505,35321.45877
1,Harlan Barnes,eu.dolor@diam.co.uk,Belize,0,40.870623,66646.89292,9572.957136,530973.9078,45115.52566
2,Naomi Rodriquez,vulputate.mauris.sagittis@ametconsectetueradip...,Algeria,1,43.152897,53798.55112,11160.355060,638467.1773,42925.70921
3,Jade Cunningham,malesuada@dignissim.com,Cook Islands,1,58.271369,79370.03798,14426.164850,548599.0524,67422.36313
4,Cedric Leach,felis.ullamcorper.viverra@egetmollislectus.net,Brazil,1,57.313749,59729.15130,5358.712177,560304.0671,55915.46248
...,...,...,...,...,...,...,...,...,...
495,Walter,ligula@Cumsociis.ca,Nepal,0,41.462515,71942.40291,6995.902524,541670.1016,48901.44342
496,Vanna,Cum.sociis.natoque@Sedmolestie.edu,Zimbabwe,1,37.642000,56039.49793,12301.456790,360419.0988,31491.41457
497,Pearl,penatibus.et@massanonante.com,Philippines,1,53.943497,68888.77805,10611.606860,764531.3203,64147.28888
498,Nell,Quisque.varius@arcuVivamussit.net,Botswana,1,59.160509,49811.99062,14013.034510,337826.6382,45442.15353
499,Marla,Camaron.marla@hotmail.com,marlal,1,46.731152,61370.67766,9391.341628,462946.4924,45107.22566

In [268]:
df.head()

,customer name,customer e-mail,country,gender,age,annual Salary,credit card debt,net worth,car purchase amount
0,Martina Avila,cubilia.Curae.Phasellus@quisaccumsanconvallis.edu,Bulgaria,0,41.851720,62812.09301,11609.380910,238961.2505,35321.45877
1,Harlan Barnes,eu.dolor@diam.co.uk,Belize,0,40.870623,66646.89292,9572.957136,530973.9078,45115.52566
2,Naomi Rodriquez,vulputate.mauris.sagittis@ametconsectetueradip...,Algeria,1,43.152897,53798.55112,11160.355060,638467.1773,42925.70921
3,Jade Cunningham,malesuada@dignissim.com,Cook Islands,1,58.271369,79370.03798,14426.164850,548599.0524,67422.36313
4,Cedric Leach,felis.ullamcorper.viverra@egetmollislectus.net,Brazil,1,57.313749,59729.15130,5358.712177,560304.0671,55915.46248

In [269]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer name        500 non-null    object
 1   customer e-mail      500 non-null    object
 2   country              500 non-null    object
 3   gender               500 non-null    int64
 4   age                  500 non-null    float64
 5   annual Salary        500 non-null    float64
 6   credit card debt     500 non-null    float64
 7   net worth            500 non-null    float64
 8   car purchase amount  500 non-null    float64
dtypes: float64(5), int64(1), object(3)
memory usage: 35.3+ KB

In [270]:
df.drop(columns=["customer name","country","customer e-mail"],inplace=True)

In [271]:
df

,gender,age,annual Salary,credit card debt,net worth,car purchase amount
0,0,41.851720,62812.09301,11609.380910,238961.2505,35321.45877
1,0,40.870623,66646.89292,9572.957136,530973.9078,45115.52566
2,1,43.152897,53798.55112,11160.355060,638467.1773,42925.70921
3,1,58.271369,79370.03798,14426.164850,548599.0524,67422.36313
4,1,57.313749,59729.15130,5358.712177,560304.0671,55915.46248
...,...,...,...,...,...,...
495,0,41.462515,71942.40291,6995.902524,541670.1016,48901.44342
496,1,37.642000,56039.49793,12301.456790,360419.0988,31491.41457
497,1,53.943497,68888.77805,10611.606860,764531.3203,64147.28888
498,1,59.160509,49811.99062,14013.034510,337826.6382,45442.15353
499,1,46.731152,61370.67766,9391.341628,462946.4924,45107.22566

In [272]:
from sklearn.model_selection import train_test_split

In [273]:
x=df.drop(columns="car purchase amount")
y=df["car purchase amount"]

In [274]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [275]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [276]:
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [277]:
x.shape

(500, 5)

In [278]:
y.shape

(500,)

In [279]:
from keras.models import Sequential
from keras.layers import Dense

In [280]:
model=Sequential([
    keras.layers.Dense(25,activation="relu",input_shape=(5,)),
    keras.layers.Dense(25,activation="relu"),
    keras.layers.Dense(1)
])

c:\Users\ACER\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [281]:
model.compile(optimizer="Adam",metrics=["mae"],loss="mean_squared_error")

In [282]:
model.fit(x=x_train,y=y_train,epochs=50)

Epoch 1/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2054117248.0000 - mae: 44052.4883
Epoch 2/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2054089472.0000 - mae: 44052.1719
Epoch 3/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2054054656.0000 - mae: 44051.7695
Epoch 4/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2054009216.0000 - mae: 44051.2461
Epoch 5/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2053946752.0000 - mae: 44050.5391
Epoch 6/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2053860096.0000 - mae: 44049.5664
Epoch 7/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2053743232.0000 - mae: 44048.2500
Epoch 8/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2053589120.0000 - mae: 44046.5156
Epoch 9/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2053389568.0000 - mae: 44044.3086
Epoch 10/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2053140352.0000 - mae: 44041.5234
Epoch 11/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2052829952.0000 - mae: 44038.1133
Epoch 12/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2052461056.0000 - mae: 44034.0391
Epoch 13/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2052010368.0000 - mae: 44029.1562
Epoch 14/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2051488256.0000 - mae: 44023.4414
Epoch 15/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2050874368.0000 - mae: 44016.7891
Epoch 16/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2050171520.0000 - mae: 44009.1602
Epoch 17/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2049354240.0000 - mae: 44000.3789
Epoch 18/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2048442752.0000 - mae: 43990.5703
Epoch 19/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2047423104.0000 - mae: 43979.4961
Epoch 20/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2046259712.0000 - mae: 43967.1211
Epoch 21/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2044975232.0000 - mae: 43953.3438
Epoch 22/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2043559936.0000 - mae: 43938.2461
Epoch 23/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2042014720.0000 - mae: 43921.7305
Epoch 24/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2040308096.0000 - mae: 43903.5312
Epoch 25/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2038430080.0000 - mae: 43883.6367
Epoch 26/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2036390912.0000 - mae: 43862.0508
Epoch 27/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2034233984.0000 - mae: 43838.9414
Epoch 28/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2031842816.0000 - mae: 43813.6836
Epoch 29/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2029239680.0000 - mae: 43786.2266
Epoch 30/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2026521600.0000 - mae: 43757.3906
Epoch 31/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2023577472.0000 - mae: 43726.3594
Epoch 32/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2020421248.0000 - mae: 43692.9883
Epoch 33/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2017131264.0000 - mae: 43658.0352
Epoch 34/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2013513600.0000 - mae: 43620.2305
Epoch 35/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2009782656.0000 - mae: 43580.6914
Epoch 36/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2005781888.0000 - mae: 43538.4688
Epoch 37/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 2001533184.0000 - mae: 43493.8164
Epoch 38/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1997132800.0000 - mae: 43447.4258
Epoch 39/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1992437248.0000 - mae: 43397.8398
Epoch 40/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1987548928.0000 - mae: 43346.1406
Epoch 41/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1982336384.0000 - mae: 43291.5312
Epoch 42/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1977023360.0000 - mae: 43234.9297
Epoch 43/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1971324672.0000 - mae: 43174.9805
Epoch 44/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1965458176.0000 - mae: 43112.8945
Epoch 45/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1959234560.0000 - mae: 43047.3906
Epoch 46/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1952906240.0000 - mae: 42980.2031
Epoch 47/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1946165888.0000 - mae: 42908.8750
Epoch 48/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1939370112.0000 - mae: 42836.0898
Epoch 49/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1932087680.0000 - mae: 42759.2539
Epoch 50/50
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 1924670464.0000 - mae: 42679.9883

In [283]:
y_pred=model.predict(x_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

In [284]:
model.evaluate(x_test,y_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1996682496.0000 - mae: 43410.3750

[1996682496.0, 43410.375]

In [285]:
print(y_test[:5])
print(y_pred[:5])

293    44736.41097
26     37161.55393
249    46135.27233
495    48901.44342
426    35784.42411
Name: car purchase amount, dtype: float64
[[1176.201 ]
 [ 856.5567]
 [1432.49  ]
 [1661.5887]
 [ 712.7706]]

In [286]:
model.save("Carmodel.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [287]:
from tensorflow import keras
import pickle as p
p.dump(sc,open("scalar.pkl","wb"))
model=keras.models.load_model("Carmodel.h5")

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [288]:
scalar_bro=p.load(open("scalar.pkl","rb"))

In [289]:
df.columns

Index(['gender', 'age', 'annual Salary', 'credit card debt', 'net worth',
       'car purchase amount'],
      dtype='object')

In [290]:
gender=int(input("Enter the gender either in 0 and 1 :- "))
age=int(input("Enter your age :- "))
salary=int(input("Enter your annual salary :- "))
credit=int(input("Enter your credit card debt :- "))
net=int(input("Enter your net worth :- "))

In [291]:
new_data=pd.DataFrame([{"gender":gender,"age":age,"annual Salary":salary,"credit card debt":credit,"net worth":net}])

In [292]:
model.summary()

Model: "sequential_11"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_33 (Dense)                │ (None, 25)             │           150 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_34 (Dense)                │ (None, 25)             │           650 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_35 (Dense)                │ (None, 1)              │            26 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 828 (3.24 KB)

 Trainable params: 826 (3.23 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 2 (12.00 B)

In [293]:
new_data=scalar_bro.transform(new_data)

In [295]:
model_output=model.predict(new_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

In [297]:
model_output[0][0]

np.float32(358413.16)