In [999]:
import pandas as pd
import numpy as np
import seaborn as sns

In [1000]:
df=pd.read_csv("Housing.csv")

In [1001]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [1002]:
df.isna().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [1003]:
df.dropna(inplace=True)

In [1004]:
df.dtypes

price                int64
area                 int64
bedrooms             int64
bathrooms            int64
stories              int64
mainroad            object
guestroom           object
basement            object
hotwaterheating     object
airconditioning     object
parking              int64
prefarea            object
furnishingstatus    object
dtype: object

In [1005]:
df.mainroad.unique()

array(['yes', 'no'], dtype=object)

In [1006]:
df["mainroad"]=df.mainroad.map({"yes":1,"no":0})

In [1007]:
df.guestroom.unique()

array(['no', 'yes'], dtype=object)

In [1008]:
df["guestroom"]=df.guestroom.map({"yes":1,"no":0})
df["basement"]=df.basement.map({"yes":1,"no":0})
df["hotwaterheating"]=df.hotwaterheating.map({"yes":1,"no":0})
df["airconditioning"]=df.airconditioning.map({"yes":1,"no":0})
df["prefarea"]=df.prefarea.map({"yes":1,"no":0})

In [1009]:
df.dtypes

price                int64
area                 int64
bedrooms             int64
bathrooms            int64
stories              int64
mainroad             int64
guestroom            int64
basement             int64
hotwaterheating      int64
airconditioning      int64
parking              int64
prefarea             int64
furnishingstatus    object
dtype: object

In [1010]:
df.furnishingstatus.unique()

array(['furnished', 'semi-furnished', 'unfurnished'], dtype=object)

In [1011]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()

In [1012]:
ohe.fit(df[["furnishingstatus"]])

OneHotEncoder()

In [1013]:
val=ohe.transform(df[["furnishingstatus"]]).toarray()

In [1014]:
feature=ohe.get_feature_names_out()

In [1015]:
feature

array(['furnishingstatus_furnished', 'furnishingstatus_semi-furnished',
       'furnishingstatus_unfurnished'], dtype=object)

In [1016]:
df[feature]=val

In [1017]:
df[feature]

,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,1.0,0.0,0.0
1,1.0,0.0,0.0
2,0.0,1.0,0.0
3,1.0,0.0,0.0
4,1.0,0.0,0.0
...,...,...,...
540,0.0,0.0,1.0
541,0.0,1.0,0.0
542,0.0,0.0,1.0
543,1.0,0.0,0.0
544,0.0,0.0,1.0

In [1018]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,furnished,1.0,0.0,0.0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,furnished,1.0,0.0,0.0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,semi-furnished,0.0,1.0,0.0
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,furnished,1.0,0.0,0.0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,furnished,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,unfurnished,0.0,0.0,1.0
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,semi-furnished,0.0,1.0,0.0
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,unfurnished,0.0,0.0,1.0
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,furnished,1.0,0.0,0.0
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,unfurnished,0.0,0.0,1.0

In [1019]:
df.drop(columns="furnishingstatus",inplace=True)

In [1020]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,1.0,0.0,0.0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,1.0,0.0,0.0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,0.0,1.0,0.0
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,1.0,0.0,0.0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,0.0,0.0,1.0
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,0.0,1.0,0.0
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,0.0,0.0,1.0
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,1.0,0.0,0.0
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,0.0,0.0,1.0

In [1021]:
x=df.drop(columns="price")

In [1022]:
y=df["price"]

In [1023]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [1024]:
x_train

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
198,5948,3,1,2,1,0,0,0,1,0,0,0.0,1.0,0.0
240,3840,3,1,2,1,0,0,0,0,1,1,0.0,1.0,0.0
214,4350,2,1,1,1,0,1,0,0,0,0,0.0,0.0,1.0
55,6000,3,1,2,1,0,0,0,1,1,0,0.0,0.0,1.0
337,2145,4,2,1,1,0,1,0,0,0,1,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401,9500,3,1,2,1,0,0,0,0,3,1,0.0,0.0,1.0
504,3185,2,1,1,1,0,0,0,1,0,0,0.0,0.0,1.0
478,3600,3,1,2,0,0,0,0,0,1,0,0.0,0.0,1.0
229,9667,4,2,2,1,1,1,0,0,1,0,0.0,1.0,0.0
170,5500,3,2,1,1,0,1,0,0,0,0,0.0,1.0,0.0

In [1025]:
y_train

198    4935000
240    4585000
214    4865000
55     7350000
337    3920000
        ...
401    3500000
504    2653000
478    2940000
229    4690000
170    5250000
Name: price, Length: 436, dtype: int64

In [1026]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [1027]:
model=lr.fit(x_train,y_train)

In [1028]:
y_pred=model.predict(x_test)

In [1029]:
y_pred

array([ 3938371.36194319,  3632140.63151177,  2277035.96701504,
        3413788.71588224,  5921986.83454087,  3052783.00888306,
        3606121.5443466 ,  3659336.00575718,  2279716.03441097,
        6785494.84137402,  3151107.4434623 ,  5108809.41150658,
        5903027.49478066,  4907995.52544174,  3198236.89556325,
        4309187.08412229,  6145528.45844784,  5647491.70049971,
        4679678.24518905,  2810505.33796962,  2599320.32169545,
        3052227.17973199,  7311573.71211678,  3449703.00122788,
        4977600.55186215,  3572810.21639545,  2693301.97765438,
        3488076.14746108,  6153325.98559637,  4168849.26131658,
        3001339.94623031,  5418250.14823283, 10469014.42949535,
        4526952.72228835,  2994074.04122962,  3464061.61526417,
        4761769.61921193,  6472181.25194249,  3043046.1090963 ,
        8207848.68890744,  4519228.58765736,  3029672.55224325,
        4391027.07265423,  3141855.87074794,  5336692.4327212 ,
        6643604.02039453,  3423782.08566099,  3808627.81245458,
        6473586.49833203,  5746283.10399904,  6530544.8295368 ,
        3757850.14689389,  2528610.1747872 ,  4128356.29609108,
        4335758.44684654,  7059802.72263048,  4035468.08040034,
        6350900.18818556,  3401439.28207474,  5197681.54680907,
        5199504.72228195,  3384031.56320851,  4534433.95631641,
        8295835.74595135,  5628717.7465409 ,  3386991.93144591,
        3769062.44743036,  6836586.85963361,  3611030.81014007,
        3229372.80584072,  3166547.66613509,  4111993.77982725,
        4700089.22958955,  5685521.12030888,  5409941.65715823,
        6469173.56349443,  5175752.90540754,  3798856.68153556,
        6492666.14441681,  8146702.22742219,  9800259.04963541,
        3764809.86756378,  5591798.46026196,  6160021.92873984,
        3002233.38145758,  3919002.74977654,  3495080.56964462,
        4523956.63889633,  7608927.79428358,  4207463.5561865 ,
        5881886.18799476,  6533706.48652375,  2759561.94227145,
        6433765.49124537,  4456987.33747331,  4612841.87415757,
        5562485.93938623,  6543117.94291608,  2449637.66642431,
        5489266.44228292,  5270286.82706175,  2607380.44578339,
        4046811.02843465,  3390475.67809883,  7297825.94796248,
        4052686.70893261,  2854404.8499125 ,  4173570.91041427,
        2784207.49433493])

In [1030]:
y_test

389    3500000
361    3710000
439    3255000
522    2380000
296    4200000
        ...
28     8400000
379    3633000
421    3360000
488    2852500
468    3010000
Name: price, Length: 109, dtype: int64

In [1031]:
from sklearn.metrics import r2_score, mean_squared_error
r2_score(y_pred,y_test)

0.6537986988379805

In [1032]:
mean_squared_error(y_pred,y_test)

938100347218.279