In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("spam.csv")

In [3]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [5]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [6]:
df["Output"]=df.Category.map({"spam":1,"ham":0})

In [7]:
df.head()

  Category                                            Message  Output
0      ham  Go until jurong point, crazy.. Available only ...       0
1      ham                      Ok lar... Joking wif u oni...       0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...       1
3      ham  U dun say so early hor... U c already then say...       0
4      ham  Nah I don't think he goes to usf, he lives aro...       0

In [8]:
df.shape

(5572, 3)

In [9]:
df.Message[2]

"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

In [10]:
x=df.Message
y=df.Output

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [12]:
x_train.shape

(4457,)

In [13]:
type(x_train)

pandas.core.series.Series

In [14]:
x_train

4       Nah I don't think he goes to usf, he lives aro...
3270                   Raviyog Peripherals bhayandar east
5267         Anything lar then ü not going home 4 dinner?
2949    Nope but i'll b going 2 sch on fri quite early...
4293                                                G.W.R
                              ...
808                     Boooo you always work. Just quit.
2050             How much is blackberry bold2 in nigeria.
939     Urgent! call 09061749602 from Landline. Your c...
3736                       It‘s £6 to get in, is that ok?
2933    Only 2% students solved this CAT question in '...
Name: Message, Length: 4457, dtype: object

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [16]:
x_train_cv=cv.fit_transform(x_train)

In [17]:
x_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59335 stored elements and shape (4457, 7751)>

In [18]:
cv.get_feature_names_out()[5000]

'optin'

In [19]:
cv.vocabulary_

{'nah': 4706,
 'don': 2425,
 'think': 6881,
 'he': 3394,
 'goes': 3195,
 'to': 6966,
 'usf': 7243,
 'lives': 4177,
 'around': 1077,
 'here': 3440,
 'though': 6899,
 'raviyog': 5615,
 'peripherals': 5191,
 'bhayandar': 1349,
 'east': 2535,
 'anything': 1006,
 'lar': 4038,
 'then': 6861,
 'not': 4852,
 'going': 3200,
 'home': 3501,
 'dinner': 2347,
 'nope': 4839,
 'but': 1587,
 'll': 4181,
 'sch': 5981,
 'on': 4961,
 'fri': 3022,
 'quite': 5567,
 'early': 2528,
 'lor': 4229,
 'cos': 2038,
 'mys': 4696,
 'sis': 6229,
 'got': 3228,
 'paper': 5101,
 'in': 3668,
 'da': 2165,
 'morn': 4608,
 'have': 3383,
 'secret': 6021,
 'admirer': 835,
 'who': 7510,
 'is': 3777,
 'looking': 4223,
 'make': 4348,
 'contact': 2005,
 'with': 7559,
 'find': 2879,
 'out': 5039,
 'they': 6874,
 'reveal': 5810,
 'thinks': 6885,
 'ur': 7222,
 'so': 6326,
 'special': 6408,
 'call': 1620,
 '09065171142': 225,
 'stopsms': 6538,
 '08718727870150ppm': 153,
 'shall': 6108,
 'get': 3145,
 'my': 4691,
 'pouch': 5375,
 'its': 3795,
 'sunny': 6635,
 'california': 1619,
 'the': 6848,
 'weather': 7438,
 'just': 3902,
 'cool': 2025,
 'friendship': 3029,
 'poem': 5321,
 'dear': 2212,
 'near': 4741,
 'can': 1645,
 'hear': 3404,
 'dont': 2429,
 'fear': 2823,
 'live': 4173,
 'cheer': 1777,
 'no': 4817,
 'more': 4606,
 'tear': 6772,
 'always': 940,
 'gud': 3288,
 'ni8': 4790,
 'lol': 4208,
 'trying': 7087,
 'your': 7719,
 'day': 2202,
 'little': 4172,
 'interesting': 3737,
 'urgent': 7225,
 'please': 5285,
 '0906346330': 215,
 'abta': 780,
 'complimentary': 1963,
 'spanish': 6401,
 'holiday': 3496,
 'or': 5003,
 '10': 263,
 '000': 1,
 'cash': 1690,
 'await': 1172,
 'collection': 1919,
 'sae': 5913,
 'cs': 2111,
 'box': 1464,
 '47': 514,
 'po19': 5301,
 '2ez': 395,
 '150ppm': 317,
 '18': 329,
 'will': 7533,
 'be': 1279,
 'of': 4914,
 'class': 1851,
 'few': 2845,
 'hours': 3543,
 'sorry': 6372,
 'are': 1055,
 'you': 7714,
 'write': 7633,
 'ccna': 1712,
 'exam': 2720,
 'this': 6888,
 'week': 7451,
 'we': 7431,
 'todays': 6972,
 'draw': 2461,
 'shows': 6178,
 'that': 6844,
 'won': 7586,
 '800': 654,
 'prize': 5459,
 'guaranteed': 3286,
 '09050000460': 170,
 'from': 3044,
 'land': 4025,
 'line': 4145,
 'claim': 1842,
 'j89': 3807,
 'po': 5300,
 'box245c2150pm': 1467,
 'ard': 1054,
 '515': 560,
 'like': 4131,
 'dat': 2193,
 'cooked': 2022,
 'rather': 5612,
 'nice': 4792,
 'salmon': 5928,
 'la': 4005,
 'lost': 4236,
 'pounds': 5378,
 'since': 6216,
 'doc': 2397,
 'visit': 7325,
 'last': 4044,
 'woot': 7596,
 'now': 4865,
 'gonna': 3209,
 'celebrate': 1719,
 'by': 1604,
 'stuffing': 6580,
 'face': 2769,
 'hi': 3453,
 'how': 3549,
 'wat': 7410,
 'tht': 6916,
 'incident': 3673,
 'use': 7237,
 'foreign': 2962,
 'stamps': 6473,
 'for': 2958,
 'whatever': 7489,
 'send': 6056,
 'them': 6857,
 'off': 4916,
 'enjoy': 2627,
 'urself': 7232,
 'tmr': 6960,
 '09090900040': 247,
 'listen': 4163,
 'extreme': 2761,
 'dirty': 2357,
 'chat': 1760,
 'office': 4925,
 'right': 5826,
 'total': 7022,
 'privacy': 5456,
 'one': 4966,
 'knows': 3986,
 'sic': 6192,
 'listening': 4166,
 '60p': 587,
 'min': 4504,
 '24': 372,
 '7mp': 647,
 '0870753331018': 91,
 'guess': 3292,
 'why': 7518,
 're': 5626,
 'worried': 7611,
 'must': 4683,
 'know': 3983,
 'there': 6867,
 'way': 7427,
 'body': 1425,
 'repairs': 5752,
 'itself': 3796,
 'and': 967,
 'sure': 6656,
 'shouldn': 6167,
 'worry': 7613,
 'take': 6718,
 'it': 3789,
 'slow': 6278,
 'first': 2895,
 'tests': 6817,
 'guide': 3297,
 'when': 7495,
 'ovulation': 5062,
 'relax': 5719,
 'nothing': 4855,
 've': 7281,
 'said': 5920,
 'reason': 5652,
 'keep': 3933,
 'followin': 2941,
 'up': 7206,
 'yar': 7681,
 'else': 2590,
 'thk': 6889,
 'all': 920,
 'sorts': 6377,
 'funny': 3074,
 'things': 6880,
 'notice': 4856,
 'shit': 6140,
 'mirror': 4523,
 'youre': 7720,
 'turning': 7108,
 'into': 3745,
 'freak': 3000,
 'over': 5056,
 'need': 4752,
 'hotel': 3536,
 'invitation': 3753,
 'had': 3315,
 'apologise': 1020,
 'cali': 1617,
 'sweet': 6684,
 'me': 4430,
 'come': 1931,
 'some': 6341,
 'english': 2626,
 'bloke': 1403,
 'weddin': 7444,
 'havent': 3386,
 'been': 1298,
 'wined': 7543,
 'dined': 2343,
 'before': 1303,
 'probably': 5465,
 'lt': 4272,
 'gt': 3282,
 'congrats': 1989,
 'mobile': 4562,
 '3g': 469,
 'videophones': 7304,
 'yours': 7722,
 '09063458130': 214,
 'videochat': 7303,
 'wid': 7522,
 'mates': 4404,
 'play': 5276,
 'java': 3829,
 'games': 3095,
 'dload': 2391,
 'polyph': 5334,
 'music': 4680,
 'noline': 4831,
 'rentl': 5749,
 'bx420': 1602,
 'ip4': 3762,
 '5we': 579,
 '150p': 313,
 'wylie': 7653,
 'tampa': 6735,
 'sarasota': 5948,
 'where': 7499,
 'do': 2394,
 'go': 3188,
 'an': 963,
 'actor': 821,
 'work': 7602,
 'evening': 2690,
 'sleep': 6258,
 'late': 4047,
 'unemployed': 7174,
 'at': 1126,
 'moment': 4584,
 'every': 2696,
 'saturday': 5961,
 'look': 4219,
 'lib': 4113,
 'stuff': 6577,
 'finish': 2885,
 'yet': 7700,
 'hey': 3449,
 'gals': 3091,
 'anyone': 1002,
 'down': 2448,
 'driving': 2478,
 'centre': 1726,
 'was': 7404,
 'gr8': 3240,
 'see': 6029,
 'message': 4479,
 'leaving': 4083,
 'what': 7488,
 'school': 5983,
 'plans': 5273,
 'sent': 6065,
 'email': 2594,
 'id': 3617,
 'soon': 6363,
 'mate': 4403,
 'spoke': 6438,
 'mag': 4329,
 'people': 5178,
 'deliver': 2252,
 'end': 2610,
 'month': 4599,
 '24th': 375,
 'sept': 6070,
 'talk': 6726,
 'later': 4049,
 'very': 7292,
 'big': 1354,
 'lambu': 4022,
 'ji': 3856,
 'vl': 7331,
 'til': 6930,
 'batchlor': 1253,
 'party': 5128,
 'ask': 1101,
 'iouri': 3760,
 'told': 6980,
 'story': 6543,
 'ten': 6797,
 'times': 6934,
 'already': 932,
 'convey': 2017,
 'regards': 5707,
 'him': 3462,
 'any': 999,
 'movie': 4629,
 'theatre': 6852,
 'watch': 7411,
 'unlimited': 7192,
 'movies': 4630,
 'pay': 5151,
 'once': 4964,
 'monday': 4588,
 'nxt': 4891,
 'completing': 1961,
 'done': 2427,
 'mths': 4651,
 'update': 7210,
 'latest': 4050,
 'orange': 5006,
 'camera': 1641,
 'video': 7302,
 'phones': 5225,
 'free': 3005,
 'save': 5965,
 'texts': 6831,
 'weekend': 7453,
 'calls': 1635,
 'text': 6821,
 'yes': 7697,
 'callback': 1623,
 'orno': 5022,
 'opt': 4998,
 'awake': 1174,
 'oh': 4936,
 'jot': 3883,
 'want': 7391,
 'remember': 5729,
 'god': 3193,
 'love': 4249,
 'has': 3370,
 'limit': 4139,
 'grace': 3244,
 'measure': 4439,
 'power': 5381,
 'boundaries': 1459,
 'may': 4421,
 'endless': 2613,
 'blessings': 1397,
 'life': 4121,
 'private': 5457,
 '2003': 356,
 'account': 801,
 'statement': 6493,
 'un': 7157,
 'redeemed': 5689,
 'points': 5324,
 '08715203652': 125,
 'identifier': 3623,
 'code': 1905,
 '42810': 498,
 'expires': 2747,
 '29': 387,
 'karnan': 3922,
 'car': 1665,
 'wait': 7367,
 'till': 6931,
 '6pm': 622,
 'directly': 2353,
 'goto': 3233,
 'doctor': 2401,
 'post': 5365,
 '1000s': 267,
 'happy': 3361,
 'reading': 5636,
 'wiv': 7566,
 'hello': 3426,
 'caroline': 1682,
 'favourite': 2821,
 'bless': 1394,
 'juz': 3907,
 'google': 3223,
 'search': 6013,
 'qet': 5552,
 'mrng': 4637,
 'hav': 3379,
 '8007': 657,
 '1st': 344,
 'no1': 4818,
 'nokia': 4827,
 'tone': 6992,
 'mob': 4561,
 'txt': 7121,
 'txting': 7125,
 'tell': 6787,
 'www': 7652,
 'getzed': 3153,
 'co': 1894,
 'uk': 7147,
 'pobox': 5302,
 '36504': 459,
 'w4': 7356,
 '5wq': 581,
 'norm': 4843,
 '16': 324,
 'didn': 2320,
 'facebook': 2770,
 'huh': 3573,
 'time': 6933,
 'should': 6165,
 'tomorrow': 6990,
 'address': 830,
 '88066': 715,
 '12': 285,
 'help': 3429,
 '0a': 261,
 'networks': 4774,
 'allow': 925,
 'companies': 1946,
 'bill': 1357,
 'sms': 6306,
 'responsible': 5791,
 'their': 6855,
 'suppliers': 6646,
 'as': 1092,
 'shop': 6151,
 'give': 3173,
 'guarantee': 3285,
 'sell': 6048,
 'wondar': 7587,
 'full': 3063,
 'flim': 2916,
 'thanks': 6837,
 'again': 869,
 'reply': 5759,
 'today': 6971,
 'visa': 7323,
 'coming': 1937,
 'still': 6521,
 'buying': 1595,
 'gucci': 3287,
 'bags': 1208,
 'sister': 6230,
 'easy': 2538,
 'uncle': 7162,
 'john': 3868,
 'also': 935,
 'his': 3469,
 'own': 5066,
 'bills': 1361,
 'really': 5647,
 'about': 771,
 'money': 4590,
 'sha': 6099,
 'explicit': 2750,
 'sex': 6091,
 '30': 434,
 'secs': 6024,
 'ring': 5831,
 '02073162414': 11,
 'costs': 2043,
 '20p': 363,
 'new': 4780,
 'theory': 6864,
 'argument': 1065,
 'wins': 7548,
 'situation': 6236,
 'loses': 4233,
 'person': 5197,
 'argue': 1063,
 'friends': 3027,
 'kick': 3951,
 'amp': 955,
 'say': 5969,
 'correct': 2034,
 'did': 2318,
 'gift': 3159,
 'year': 7689,
 'didnt': 2321,
 'bad': 1203,
 'well': 7466,
 'if': 3629,
 'desperate': 2289,
 'armand': 1072,
 'mum': 4666,
 'buy': 1592,
 'food': 2949,
 'jazz': 3833,
 'yoga': 7710,
 'hip': 3466,
 'hop': 3516,
 'kb': 3930,
 'yogasana': 7711,
 'unsubscribed': 7202,
 'services': 6079,
 'tons': 7001,
 'sexy': 6093,
 'babes': 1194,
 'hunks': 3582,
 'straight': 6545,
 'phone': 5222,
 'http': 3564,
 'gotbabes': 3231,
 'subscriptions': 6601,
 'doing': 2417,
 'yuou': 7734,
 'working': 7605,
 'getting': 3152,
 'pc': 5160,
 'mom': 4583,
 'spot': 6448,
 'would': 7623,
 'someone': 6345,
 'asked': 1103,
 'our': 5036,
 'dating': 2197,
 'service': 6078,
 'cant': 1657,
 '09058095107': 188,
 'revealed': 5811,
 's3xy': 5906,
 'swing': 6691,
 'bit': 1374,
 'care': 1670,
 'firsg': 2894,
 'book': 1437,
 'status': 6496,
 'frequently': 3018,
 'table': 6707,
 'occupied': 4906,
 'waiting': 7370,
 'tree': 7062,
 'hmm': 3482,
 'ill': 3642,
 'ok': 4941,
 'forgiven': 2968,
 'payasam': 5152,
 'rinu': 5837,
 'brings': 1524,
 'msg': 4640,
 'content': 2007,
 'order': 5009,
 'resent': 5773,
 'previous': 5439,
 'attempt': 1135,
 'failed': 2779,
 'due': 2504,
 'network': 4772,
 'error': 2662,
 'queries': 5558,
 'customersqueries': 2153,
 'netvision': 4771,
 'com': 1926,
 'madam': 4325,
 'regret': 5711,
 'disturbance': 2380,
 'might': 4495,
 'receive': 5664,
 'reference': 5693,
 'check': 1769,
 'dlf': 2390,
 'premarica': 5416,
 'kindly': 3967,
 'informed': 3705,
 'rgds': 5817,
 'rakhesh': 5594,
 'kerala': 3941,
 'prob': 5464,
 '078': 33,
 'hot': 3535,
 'fantasies': 2801,
 '08707509020': 90,
 'per': 5180,
 'ntt': 4874,
 'ltd': 4273,
 '1327': 299,
 'croydon': 2103,
 'cr9': 2070,
 '5wb': 578,
 '0870': 70,
 'national': 4730,
 'rate': 5610,
 'practising': 5394,
 'curtsey': 2145,
 'am': 942,
 'marriage': 4388,
 'function': 3067,
 'stand': 6474,
 'away': 1177,
 'doesn': 2408,
 'heart': 3408,
 'ache': 805,
 'without': 7562,
 'wonder': 7589,
 'crave': 2078,
 'lunch': 4284,
 'menu': 4472,
 'only': 4972,
 'great': 3262,
 'escape': 2667,
 'fancy': 2799,
 'bridge': 1514,
 'needs': 4756,
 'her': 3439,
 'lager': 4018,
 'tomo': 6988,
 '09094100151': 248,
 'mins': 4517,
 'cast': 1695,
 '10p': 275,
 'vary': 7275,
 'provided': 5506,
 'aom': 1012,
 'gbp5': 3121,
 'box61': 1476,
 'm60': 4306,
 '1er': 338,
 'until': 7204,
 'stop': 6530,
 'ages': 876,
 'true': 7079,
 'passable': 5131,
 'high': 3457,
 'score': 5989,
 'apply': 1031,
 'phd': 5215,
 '5years': 582,
 'salary': 5923,
 'makes': 4349,
 'easier': 2533,
 'aiya': 896,
 'discuss': 2370,
 'pick': 5235,
 'aight': 889,
 'fb': 2822,
 'couple': 2056,
 'minutes': 4520,
 'number': 4880,
 'awarded': 1176,
 '2000': 355,
 '09058094454': 180,
 '3030': 439,
 'valid': 7264,
 '12hrs': 295,
 'wednesday': 7448,
 'bring': 1522,
 'mini': 4510,
 'cheetos': 1782,
 'bag': 1207,
 'somewhere': 6354,
 'beneath': 1328,
 'pale': 5088,
 'moon': 4604,
 'light': 4127,
 'dreams': 2465,
 'goodnite': 3218,
 'babe': 1193,
 'im': 3644,
 'wanna': 7389,
 'something': 6349,
 'xx': 7665,
 'sez': 6095,
 'hows': 3554,
 'de': 2207,
 'arab': 1051,
 'boy': 1479,
 'hope': 3517,
 'good': 3211,
 'evry1': 2714,
 'ya': 7674,
 'eshxxxxxxxxxxx': 2669,
 'mobiles': 4563,
 '2004': 357,
 '89545': 726,
 'collect': 1916,
 'tc': 6760,
 'biz': 1380,
 '2optout': 418,
 '087187262701': 147,
 '50gbp': 551,
 'mtmsg18': 4653,
 'txtauction': 7123,
 'coast': 1896,
 'miss': 4529,
 'khelate': 3949,
 'kintu': 3969,
 'opponenter': 4993,
 'dhorte': 2310,
 'lage': 4017,
 'thats': 6847,
 'rule': 5891,
 'receiving': 5667,
 'quality': 5555,
 'outside': 5051,
 'players': 5279,
 'allowed': 926,
 'treat': 7058,
 'deepest': 2235,
 'darkest': 2184,
 '09094646631': 249,
 '08712460324': 114,
 'nat': 4725,
 'dad': 2169,
 'wan': 7386,
 'stay': 6497,
 'meh': 4454,
 'chikku': 1800,
 'abt': 779,
 'staff': 6467,
 'placement': 5264,
 'training': 7039,
 'amrita': 958,
 'college': 1921,
 'admin': 833,
 'building': 1566,
 'slightly': 6270,
 'earlier': 2526,
 'reaching': 5630,
 'were': 7475,
 'together': 6975,
 'thinkin': 6883,
 'meet': 4447,
 'bugis': 1564,
 '930': 740,
 'crucify': 2105,
 'ringtoneking': 5835,
 '84484': 694,
 'back': 1201,
 'brum': 1545,
 'putting': 5546,
 'us': 7233,
 'keeping': 3934,
 'dhoni': 2309,
 'luck': 4277,
 'win': 7535,
 'title': 6947,
 'join': 3869,
 'noe': 4821,
 'ben': 1326,
 'lovely': 4252,
 'night': 4800,
 'wake': 7371,
 'smile': 6294,
 'knowing': 3984,
 'morning': 4610,
 'weeks': 7456,
 'savamob': 5964,
 'member': 4461,
 'offers': 4924,
 'accessible': 791,
 '08709501522': 96,
 'details': 2295,
 '139': 300,
 'la3': 4007,
 '2wu': 430,
 '50': 545,
 'happen': 3351,
 'tonight': 6998,
 'die': 2323,
 'family': 2794,
 'set': 6082,
 'stone': 6528,
 'except': 2723,
 'sunday': 6633,
 'goodnight': 3217,
 'fix': 2900,
 'ready': 5637,
 'dearly': 2215,
 'missed': 4531,
 'mila': 4498,
 'age23': 873,
 'blonde': 1405,
 'guys': 3306,
 'fun': 3066,
 'mtalk': 4649,
 '69866': 609,
 '30pp': 441,
 '5free': 571,
 'increments': 3686,
 'help08718728876': 3431,
 'friend': 3026,
 'round': 5869,
 'ish': 3780,
 'pandy': 5092,
 'joined': 3870,
 '4w': 540,
 'technologies': 6778,
 'job': 3863,
 'started': 6486,
 'skye': 6250,
 'plz': 5298,
 'ans': 988,
 'bslvyl': 1547,
 'via': 7295,
 'fullonsms': 3064,
 'called': 1627,
 'instead': 3729,
 'never': 4777,
 'much': 4658,
 'came': 1640,
 'made': 4326,
 'truly': 7081,
 'forget': 2965,
 'gbp': 3120,
 'gym': 3308,
 'harri': 3368,
 'alex': 913,
 'nichols': 4793,
 'management': 4362,
 'puzzeles': 5547,
 'wherre': 7503,
 'boytoy': 1484,
 'slave': 6257,
 'pictures': 5242,
 'yourself': 7723,
 'bright': 1517,
 'cell': 1723,
 'says': 5973,
 'being': 1314,
 'both': 1454,
 'fine': 2882,
 'received': 5666,
 'understood': 7172,
 'acted': 813,
 'upon': 7216,
 'st': 6464,
 'andre': 968,
 'virgil': 7320,
 'cream': 2083,
 '09058091854': 179,
 'box385': 1471,
 'm6': 4305,
 '6wu': 625,
 'hmmm': 3483,
 'change': 1741,
 'field': 2851,
 'quickly': 5564,
 'system': 6703,
 'administrator': 834,
 'coffee': 1906,
 'run': 5895,
 'believe': 1315,
 'wif': 7524,
 'booking': 1439,
 'tour': 7029,
 'package': 5075,
 'princess': 5449,
 'catch': 1699,
 'strong': 6562,
 'hands': 3339,
 'gandhipuram': 3097,
 'walk': 7374,
 'cross': 2101,
 'cut': 2154,
 'road': 5843,
 'side': 6194,
 'street': 6550,
 'turn': 7106,
 'pls': 5293,
 'nuerologist': 4878,
 'gumby': 3302,
 'cheese': 1780,
 'pizza': 5261,
 'doin': 2416,
 'problem': 5466,
 'taxi': 6753,
 'ing': 3708,
 'tuesday': 7099,
 'cinema': 1837,
 'which': 7505,
 'wanted': 7393,
 'short': 6156,
 'edge': 2550,
 'laptop': 4037,
 'after': 864,
 'air': 892,
 'balloon': 1218,
 'chance': 1739,
 'evaporated': 2686,
 'violated': 7316,
 'stealing': 6505,
 'employer': 2606,
 'paperwork': 5103,
 'report': 5761,
 'supervisor': 6644,
 'whenever': 7496,
 'hero': 3441,
 'qatar': 5550,
 'tonite': 7000,
 'apt': 1047,
 'opportunity': 4994,
 'touch': 7025,
 'cozy': 2066,
 'exhausted': 2734,
 'nobody': 4820,
 'went': 7472,
 'everything': 2703,
 'closed': 1872,
 'mmmmm': 4553,
 'loved': 4250,
 'waking': 7372,
 'words': 7601,
 'too': 7002,
 'able': 770,
 'ful': 3061,
 'song': 6358,
 'lyrics': 4299,
 'theyre': 6875,
 'lots': 4239,
 'places': 5265,
 'hospitals': 3532,
 'medical': 4443,
 'safe': 5915,
 'slp': 6281,
 'swt': 6695,
 'muah': 4657,
 'jay': 3830,
 'put': 5544,
 'aiyar': 898,
 'poor': 5344,
 'thing': 6879,
 'support': 6649,
 'jia': 3857,
 'sunshine': 6638,
 'quiz': 5570,
 'wkly': 7572,
 'top': 7009,
 'sony': 6360,
 'dvd': 2518,
 'player': 5278,
 'country': 2053,
 'liverpool': 4176,
 'played': 5277,
 'mid': 4491,
 'ansr': 989,
 '82277': 674,
 'sp': 6394,
 'tyrone': 7135,
 'raji': 5590,
 'favour': 2820,
 'birthday': 1372,
 'wishes': 7554,
 'nimya': 4806,
 'fucking': 3055,
 'chickened': 1797,
 'messaged': 4480,
 ...}

In [23]:
x_train_np=x_train_cv.toarray()

In [24]:
x_train_np

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4457, 7751))

In [25]:
x_train_np.shape

(4457, 7751)

In [27]:
np.where(x_train_np[5]!=0)

(array([ 153,  225,  835, 1620, 2005, 2879, 3383, 3777, 4223, 4348, 4961,
        5039, 5810, 6021, 6326, 6408, 6538, 6874, 6885, 7222, 7510, 7559]),)

In [29]:
x_train[5]

"FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv"

In [30]:
y_train[5]

np.int64(1)

In [33]:
from sklearn.naive_bayes import MultinomialNB
MB=MultinomialNB()

In [35]:
model=MB.fit(x_train_np,y_train)
model

MultinomialNB()

In [37]:
x_test_cv=cv.transform(x_test)

In [38]:
x_test_np=x_test_cv.toarray()

In [40]:
y_pred=model.predict(x_test_np)

In [42]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9865470852017937

In [43]:
eg=["FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv",
    "As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune"]

In [45]:
lasan=cv.transform(eg)

In [46]:
model.predict(lasan)

array([0, 0])