In [163]:
import pandas as pd
import numpy as np
import seaborn as sns

In [164]:
df=pd.read_csv("Housing.csv")

In [165]:
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [166]:
df.isna().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [167]:
df.dropna(inplace=True)

In [168]:
df.dtypes

price                int64
area                 int64
bedrooms             int64
bathrooms            int64
stories              int64
mainroad            object
guestroom           object
basement            object
hotwaterheating     object
airconditioning     object
parking              int64
prefarea            object
furnishingstatus    object
dtype: object

In [169]:
df.mainroad.unique()

array(['yes', 'no'], dtype=object)

In [170]:
df["mainroad"]=df.mainroad.map({"yes":1,"no":0})

In [171]:
df.guestroom.unique()

array(['no', 'yes'], dtype=object)

In [172]:
df["guestroom"]=df.guestroom.map({"yes":1,"no":0})
df["basement"]=df.basement.map({"yes":1,"no":0})
df["hotwaterheating"]=df.hotwaterheating.map({"yes":1,"no":0})
df["airconditioning"]=df.airconditioning.map({"yes":1,"no":0})
df["prefarea"]=df.prefarea.map({"yes":1,"no":0})

In [173]:
df.furnishingstatus.unique()

array(['furnished', 'semi-furnished', 'unfurnished'], dtype=object)

In [174]:
x=df.drop(columns="price")

In [175]:
y=df["price"]

In [176]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [177]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(drop="first",sparse_output=False)

In [178]:
x_train_ohe=ohe.fit_transform(x_train[["furnishingstatus"]])
x_test_ohe=ohe.transform(x_test[["furnishingstatus"]])

In [179]:
feature=ohe.get_feature_names_out(["furnishingstatus"])

In [180]:
x_train_ohe=pd.DataFrame(x_train_ohe, columns=feature)
x_test_ohe=pd.DataFrame(x_test_ohe, columns=feature)

In [181]:
x_train=x_train.reset_index(drop=True)
x_test=x_test.reset_index(drop=True)

In [182]:
x_train=x_train.drop(columns="furnishingstatus")
x_test=x_test.drop(columns="furnishingstatus")

In [183]:
x_train=pd.concat([x_train,x_train_ohe],axis=1)
x_test=pd.concat([x_test,x_test_ohe],axis=1)

In [184]:
x_train[feature]=x_train_ohe
x_test[feature]=x_test_ohe

In [185]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [186]:
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [187]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [188]:
model=lr.fit(x_train,y_train)

In [189]:
y_pred=model.predict(x_test)

In [190]:
y_pred

array([5164653.90033967, 7224722.29802166, 3109863.24240338,
       4612075.3272256 , 3294646.25725956, 3532275.09556558,
       5611774.56836474, 6368145.98732718, 2722856.95689986,
       2629405.61585783, 9617039.50315578, 2798087.30447888,
       3171096.76847064, 3394639.09125529, 3681088.65424276,
       5263187.74621486, 3035963.47612386, 4786122.8004005 ,
       4349551.9200572 , 3572362.09930451, 5774875.21395649,
       5886993.57919883, 2730836.19518459, 4727316.47323636,
       5244847.52716799, 7555324.21605601, 3220790.84680269,
       5191898.79934207, 8143726.91009782, 3398814.09825036,
       6490693.05027925, 3315105.90747811, 6708457.36761325,
       4201738.21071676, 3557571.06735186, 5836974.50478626,
       4808660.67448475, 4362878.73613262, 3191242.95701508,
       4596554.93225239, 4566042.8604841 , 3517779.52374149,
       7205844.79365835, 3983597.27861103, 3749338.70271055,
       4274731.09125895, 6757442.10783741, 4037320.43665851,
       3769334.90397125, 3417627.44377157, 7268416.6764461 ,
       2802534.35431385, 4341750.61420451, 4516422.15345642,
       3679997.65037847, 2678959.06481153, 7498029.17782458,
       2920366.45493168, 4239582.0596018 , 2766467.48467034,
       4841309.85933273, 3584359.56014923, 5142140.84897579,
       4221869.20996263, 4698408.50824081, 4662380.98564313,
       7177841.51216424, 3452198.91383761, 5902436.91361411,
       6198094.31822812, 4773218.99689078, 5178933.32585697,
       4490410.96106558, 7968737.41567512, 3519394.94792196,
       5501905.04909554, 3947055.15571396, 4714056.36707951,
       4792291.26764381, 4250596.74659378, 7718149.1935735 ,
       4053241.11775758, 6453918.60757725, 5355571.58680278,
       2755188.29175271, 6796008.09793359, 2607277.38176332,
       3679738.85761988, 7968276.12638737, 8078480.59500816,
       3266213.77309708, 5897888.53031041, 3569461.07439185,
       3868964.98032521, 7584429.5312489 , 4740586.43771692,
       5139372.69032253, 6423485.10228601, 4914078.82258489,
       5982087.31289315, 3855027.32194281, 6420308.27282365,
       3749108.5131483 , 5998642.37204433, 4973331.10029252,
       4336650.86896383, 7059062.72274841, 6398940.86831986,
       6363889.85312644])

In [191]:
y_test

316    4060000
77     6650000
360    3710000
90     6440000
493    2800000
        ...
15     9100000
357    3773000
39     7910000
54     7350000
155    5530000
Name: price, Length: 109, dtype: int64

In [192]:
from sklearn.metrics import r2_score
r2_score(y_pred,y_test)

0.27264433806254296

In [193]:
import pickle
pickle.dump(lr,open("model.pkl","wb"))
pickle.dump(sc,open("scalar.pkl","wb"))
pickle.dump(ohe,open("encoder.pkl","wb"))

In [194]:
our_model=pickle.load(open("model.pkl","rb"))
our_scaler=pickle.load(open("scalar.pkl","rb"))
our_encoder=pickle.load(open("encoder.pkl","rb"))

In [195]:
#columns input btw

df.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [196]:
# area=int(input("Enter the area :- "))
# bedrooms=int(input("Enter the bedrooms :- "))
# bathrooms=int(input("Enter the bathrooms :- "))
# stories=int(input("Enter the stories :- "))
# mainroad=int(input("Enter the mainroad yes(1) or no(0):- "))
# guestroom=int(input("Enter the guestroom yes(1) or no(0):- "))
# basement=int(input("Enter the basement yes(1) or no(0):- "))
# hotwaterheating=int(input("Enter the hotwaterheating yes(1) or no(0):- "))
# airconditioning=int(input("Enter the airconditioning yes(1) or no(0):- "))
# parking=int(input("Enter the parking :- "))
# prefarea=int(input("Enter the prefarea :- "))
# furnishingstatus=input("Enter the furnishingstatus(furnished/semi-furnished/unfurnished) :- ")

In [197]:
# new_pred=pd.DataFrame([{"area":area
#                     ,"bedrooms":bedrooms,
#                     "stories":stories,
#                     'mainroad':mainroad,
#        'guestroom':guestroom, 'basement':basement, 'hotwaterheating':hotwaterheating, 'airconditioning':airconditioning,
#        'parking':parking, 'prefarea':prefarea, 'furnishingstatus':furnishingstatus}])

In [198]:
new_data = pd.DataFrame([{
    "area": 2000,
    "bedrooms": 3,
    "bathrooms": 2,
    "stories": 2,
    "mainroad": 1,
    "guestroom": 0,
    "basement": 1,
    "hotwaterheating": 0,
    "airconditioning": 1,
    "parking": 2,
    "prefarea": 0,
    "furnishingstatus": "semi-furnished"
}])

In [199]:
new_data

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,2000,3,2,2,1,0,1,0,1,2,0,semi-furnished

In [200]:
new_ohe=our_encoder.transform(new_data[["furnishingstatus"]])
new_data=new_data.drop(columns="furnishingstatus")
new_data[our_encoder.get_feature_names_out()]=new_ohe

In [201]:
new_data

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,2000,3,2,2,1,0,1,0,1,2,0,1.0,0.0

In [202]:
new_data=our_scaler.transform(new_data)

In [203]:
output=our_model.predict(new_data)

In [204]:
output[0]

np.float64(5838548.702436365)